GET_PATH_GLOBS = %w[
  *a.asp
  *a.aspx
  *a.aspx*b
  *a.do
  *a.mvc
  *a.php
  *a.php/*b
  *a/.env
  *a/GetQrCodeInfo
  *a/admin
  *a/admin/*b
  *a/aws.yml
  *a/fckeditor/*b
  *a/getTheLotteryInitList
  *a/index.php/*b
  *a/phpinfo
  *a/queryOfficePage
  *a/wp-includes/*b
  /!==this.readyState
  /*a/phpunit/*b
  /.*b
  /1
  /2018
  /2019
  /2020
  /2021
  /2022
  /360/static/js/iku.js
  /Content/*b
  /FCKeditor/*b
  /Home/Bind/binding
  /Home/GetAllGameCategory
  /Home/Index/ajaxTJ
  /Login
  /Pc/Lang/index.html
  /Public/*b
  /Scripts/common.js
  /Security/login
  /Templates/*b
  /_wpeprivate/*b
  /actuator/env
  /adm
  /admin
  /admin/*b
  /administrator
  /administrator/language/en-GB/en-GB.xml
  /ajax
  /ajax/*b
  /api/*b
  /apis/*b
  /appxz/index.html
  /assets/res/mods/room.js
  /auth
  /aws.yml
  /backup
  /bak
  /base/exchange_article/index/classid/1/id/1
  /base/exchange_index/changepwdfirst
  /bc
  /bk
  /blog
  /cache
  /cdn-cgi/*b
  /cgi-bin/*b
  /client/api/findConfigByKey
  /client/api/findFreeTrade
  /cms
  /common/member/js/user.util.js
  /common/template/lottery/lecai/css/style.css
  /components/*b
  /config.js
  /contact
  /contacts
  /cscpLoginWeb/*b
  /csjs/bankCheck.js
  /css/all.css
  /css/app.css
  /css/main.css
  /css/nsc/reset.css
  /data/json/config.json
  /demo
  /demo/*b
  /dev/
  /dev/*b
  /env
  /fckeditor/*b
  /files
  /files/pub_rem.js
  /friendGroup/list
  /gaocc/g445g
  /h5
  /homes
  /im
  /im/App/config
  /im/h5
  /im/in/GetUuid
  /images
  /images/no.jpg
  /images/src_images_but_dianz_s.png
  /index/Mobile/kline_week
  /index/index/purchase.html
  /infe/rest/flash/getServerIP.json
  /install
  /ipl/app/flash/publicbmw/ball/FigLeaf.js
  /jiaoyimao/default.css
  /js/basic.js
  /js/common.js
  /js/home.js
  /js/mage/cookies.js
  /kkrps/im_group/*b
  /langConfig.js
  /loan
  /login.html
  /m
  /m/ticker/usdtqc
  /magento/*b
  /magento_version
  /main
  /manager
  /market/getStockBaseInfo
  /member/js/lang_zh_CN.js
  /n/news/banner
  /new
  /new-site
  /nyyh/game.css
  /old
  /old-site
  /old-wp
  /old/*b
  /oldsite
  /otc
  /pages/admin
  /pages/console/*b
  /phpMyAdmin
  /phpinfo
  /phpmyadmin/*b
  /plugins/*b
  /proxy/games
  /proxy/settings
  /public/*b
  /resources/css/headernav.css
  /resources/main/common.js
  /room/getRoomBangFans
  /room/script/face.js
  /rss/*b
  /s_api/basic/*b
  /sftp-config.json
  /shop/*b
  /simpla
  /site
  /site.js
  /site/get-hq
  /sites/default/files
  /staging/*b
  /static/*b
  /statics/js/API.js
  /stock/search
  /store/*b
  /temp
  /template/920ka/js/woodyapp.js
  /template/js/comm/Confrim.js
  /test
  /test/*b
  /tmp
  /uploads
  /user/userlist
  /v1
  /v2
  /views/commData/commonSite.js
  /wap/api/exchangerateuserconfig!get.action
  /wap/trading/get_newallorder_ajax
  /web
  /web/api/getBanner
  /webadmin
  /wordpress
  /wp
  /wp-admin
  /wp-admin/*b
  /wp-config-backup
  /wp-config-good
  /wp-config.*b
  /wp-config_good
  /wp-content
  /wp-content/*b
  /wp-includes
  /wp-includes/*b
  /wp-json
  /wp-json/*b
  /wp1
  /wp2
  /www.rar
  /www.sql
  /xianyu/*b
  /xxsssseee
  /xy
].freeze

POST_PATH_GLOBS = %w[
  *a.php
  /
  /melody/api/v1/pageconfig/list
  /user/getAllNicknames
].freeze

DELETE_PATH_GLOBS = %w[
  /contacts
].freeze

IronTeapot::Engine.routes.draw do
  GET_PATH_GLOBS.each do |path|
    get path, controller: 'teapots', action: 'coffee'
  end

  POST_PATH_GLOBS.each do |path|
    post path, controller: 'teapots', action: 'coffee'
  end

  DELETE_PATH_GLOBS.each do |path|
    delete path, controller: 'teapots', action: 'coffee'
  end
end
