get:
  - '*a.ashx'
  - '*a.asp'
  - '*a.aspx'
  - '*a.aspx*b'
  - '*a.cgi'
  - '*a.do'
  - '*a.env'
  - '*a.git/*b'
  - '*a.mvc'
  - '*a.php'
  - '*a.php/*b'
  - '*a.php4'
  - '*a.php5'
  - '*a.php7'
  - '*a.sql'
  - '*a/ALFA_DATA'
  - '*a/GetQrCodeInfo'
  - '*a/Telerik.Web.UI.WebResource.axd'
  - '*a/_ignition/*b'
  - '*a/admin'
  - '*a/admin/*b'
  - '*a/ajax.js'
  - '*a/alfacgiapi/'
  - '*a/alfacgiapi/*b'
  - '*a/api-docs'
  - '*a/app.js'
  - '*a/aws.yml'
  - '*a/cgialfa'
  - '*a/ckeditor/*b'
  - '*a/config.json'
  - '*a/config/*b'
  - '*a/dropzone-amd-module.*b'
  - '*a/dropzone.js'
  - '*a/dup-installer'
  - '*a/elfinder.html'
  - '*a/elfinder/*b'
  - '*a/env'
  - '*a/environment.ts'
  - '*a/fckeditor/*b'
  - '*a/filemanager'
  - '*a/getTheLotteryInitList'
  - '*a/index.php/*b'
  - '*a/jquery.filer/*b'
  - '*a/kcfinder'
  - '*a/kcfinder/js/helper.js'
  - '*a/license.txt'
  - '*a/magmi'
  - '*a/maven/com.atlassian.jira/jira-webapp-dist/pom.properties'
  - '*a/media/system/js/core.js'
  - '*a/mt-static/mt.js'
  - '*a/nextcloud.log'
  - '*a/owncloud.log'
  - '*a/phpinfo'
  - '*a/plupload'
  - '*a/plupload/*b'
  - '*a/queryOfficePage'
  - '*a/server/php'
  - '*a/settings.py'
  - '*a/sftp-config.json'
  - '*a/sftp.json'
  - '*a/tinymce'
  - '*a/wallet.dat'
  - '*a/wp-admin'
  - '*a/wp-admin/*b'
  - '*a/wp-content'
  - '*a/wp-content/*b'
  - '*a/wp-includes'
  - '*a/wp-includes/*b'
  - '*a/wp-json'
  - '*a/wp-json/*b'
  - '/tools/.env '
  - /!==this.readyState
  - /*a/phpunit
  - /*a/phpunit/*b
  - /.*b
  - /0byte
  - /1
  - /1111/feed
  - /123
  - /2009
  - /2010
  - /2012
  - /2013
  - /2014
  - /2015
  - /2016
  - /2017
  - /2018
  - /2019
  - /2020
  - /2021
  - /2022
  - /360/static/js/iku.js
  - /97bwag
  - /ALFA_DATA
  - /Adminhtml_category
  - /BACKUP
  - /BAK
  - /BKP
  - /BLOG
  - /Backoffice
  - /Backup
  - /Blog
  - /Cache
  - /Content/*b
  - /DEMO
  - /Deadcode1975xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  - /Demo
  - /FCKeditor/*b
  - /FORUM
  - /FileZilla
  - /Home/Bind/binding
  - /Home/GetAllGameCategory
  - /Home/Index/ajaxTJ
  - /Login
  - /MYzoomsounds
  - /NEW
  - /New
  - /OLD
  - /OLDSITE
  - /Old
  - /PSBC-1
  - /Panels.txt
  - /Pc/Lang/index.html
  - /Public/*b
  - /SHOP
  - /SITE
  - /STORE
  - /Scripts/common.js
  - /Security/login
  - /Shop
  - /Site
  - /TEST
  - /Telerik.Web.UI.WebResource.axd
  - /Template/Mobile/js/main.js
  - /Templates/*b
  - /Test
  - /Tmp
  - /WORDPRESS
  - /WP
  - /WWW
  - /WordPress
  - /Wordpress
  - /Wp
  - /Www
  - /_all_dbs
  - /_aws/credentials
  - /_ignition/*b
  - /_profiler
  - /_profiler/empty/search/results
  - /_site
  - /_wpeprivate/*b
  - /account.json
  - /accounts.json
  - /actions/seomatic/meta-container/all-meta-containers
  - /adm
  - /admin
  - /admin/*b
  - /adminer
  - /adminer-4.*b
  - /adminer.*b
  - /administration/vendor/
  - /administrator
  - /administrator/components/
  - /administrator/components/com_facileforms/libraries/jquery/tooltip.js
  - /administrator/components/com_xcloner-backupandrestore_old/
  - /administrator/help/*b
  - /administrator/language/en-GB/en-GB.xml
  - /administrator/language/en-GB/install.xml
  - /administrator/manifests/files/joomla.xml
  - /administrator/templates/
  - /administrator/templates/bluestork/
  - /administrator/templates/hathor
  - /administrator/templates/isis/
  - /ajax
  - /ajax/*b
  - /akismet
  - /alfacgiapi
  - /alfacgiapi/*b
  - /amember/admin-users
  - /amfeed/main/download
  - /analytics/jbips
  - /api-docs
  - /api.py
  - /api/*b
  - /apis/*b
  - /app
  - /app/*b
  - /application
  - /application/*b
  - /appxz/index.html
  - /article/image7/
  - /asset/js/library/filer/examples/default/index.html
  - /assets
  - /assets/app-manifest.json
  - /assets/app.config.json
  - /assets/credentials.json
  - /assets/dist/static/js/vendor_prod.js
  - /assets/extension/market/css/mt4.css
  - /assets/js/uploadify/uploadify.css
  - /assets/plugins
  - /assets/res/mods/room.js
  - /assets/room/css/room_mobile.css
  - /assets/scripts
  - /assets/server
  - /auth
  - /auth/oauth/token
  - /authentik.yaml
  - /aws.credentials
  - /aws.yml
  - /aws/.credentials
  - /aws/config
  - /aws/credentials
  - /bac
  - /back
  - /back.*b
  - /backup
  - /backup-new
  - /backup.*b
  - /backup/vendor
  - /bak
  - /base/exchange_article/index/classid/1/id/1
  - /base/exchange_index/changepwdfirst
  - /bc
  - /bea_wls_internal
  - /beta
  - /bin/bash
  - /bk
  - /bkp
  - /bkp-two
  - /bkp2
  - /block-patterns
  - /block-supports
  - /blocks
  - /blog
  - /blogs
  - /browser
  - /cache
  - /cart
  - /ccaef.txt
  - /cdn-cgi/*b
  - /cgi-bin/*b
  - /cgialfa
  - /ch/upload/upload
  - /cjs/*c.js
  - /ckeditor/*b
  - /cli
  - /client/api/findConfigByKey
  - /client/api/findFreeTrade
  - /cms
  - /cms/adMInhtml_page
  - /common/member/js/user.util.js
  - /common/template/lottery/lecai/css/style.css
  - /components/*b
  - /conf.json
  - /config
  - /config/*b
  - /configuration.json
  - /configuration.php_old
  - /configuration/info.xml
  - /contact
  - /contacts
  - /copy
  - /core
  - /cpanel
  - /credentials
  - /credentials/*b
  - /cscpLoginWeb/*b
  - /csjs/bankCheck.js
  - /css/album.css
  - /css/all.css
  - /css/app.css
  - /css/main.css
  - /css/nsc/reset.css
  - /css/style.css
  - /css/view/main/*b
  - /cubrid
  - /database
  - /db
  - /debug/default/view
  - /demo
  - /demo/*b
  - /dev/
  - /dev/*b
  - /devnew
  - /dist/images/mask/guide/cn/step1.jpg
  - /docs/_sidebar.md
  - /docs/swagger.json
  - /downloader
  - /dump.*b
  - /ecoin
  - /ecosystem.config.json
  - /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application
  - /env
  - /env-config.json
  - /env.config.js
  - /env/config
  - /environment.rb
  - /environments/.aws/.credentials
  - /environments/.credentials
  - /error_log
  - /eval-stdin
  - /explore/projects
  - /fckeditor/*b
  - /feed
  - /file
  - /filemanager
  - /files
  - /files/pub_rem.js
  - /files/pub_reset.css
  - /filezilla.xml
  - /fonts
  - /fonts/Playfair_Display
  - /forum
  - /forum/slide_img_19/
  - /forums/
  - /friendGroup/list
  - /gaocc/g445g
  - /good.txt
  - /good_admin.txt
  - /graphql
  - /gsgvvt
  - /guacamole/api/tokens
  - /h5
  - /h5/static/*b
  - /hehe
  - /helpers
  - /helpers/utility.js
  - /home
  - /home/login/login_index.html
  - /homes
  - /hooks
  - /html
  - /html.bak
  - /html.bck
  - /html.old
  - /html.rar
  - /html.tmp
  - /html.txt
  - /html.zip
  - /ibase
  - /icons
  - /iframe/rankgiftgotapi/1005
  - /im
  - /im/App/config
  - /im/h5
  - /im/in/GetUuid
  - /images
  - /images/editor/separator.gif
  - /images/fenetres/
  - /images/fenetres/fenetresbb/
  - /images/glogo.jpg
  - /images/glogo2.png
  - /images/go-button-gateway.gif
  - /images/no.jpg
  - /images/petabox-header.png
  - /images/src_images_but_dianz_s.png
  - /img
  - /img/login.png
  - /img/pdf/
  - /include/
  - /include/mapping_regions/
  - /includes
  - /includes/
  - /index.js
  - /index/Mobile/*b
  - /index/index/purchase.html
  - /index/login/register
  - /infe/rest/fig/advertise/common.json
  - /infe/rest/flash/getServerIP.json
  - /info
  - /install
  - /installation
  - /ipl/app/flash/publicbmw/ball/FigLeaf.js
  - /issmall
  - /jars/upload/
  - /jiaoyimao/default.css
  - /jquery.filer/*b
  - /js/a.script
  - /js/app.js
  - /js/app.ling.js
  - /js/basic.js
  - /js/chat/chat.js
  - /js/common.js
  - /js/config.js
  - /js/envConfig.js
  - /js/header-rollup-554.js
  - /js/home.js
  - /js/json.js
  - /js/mage/cookies.js
  - /js/main.js
  - /js/pups.js
  - /json/configs/permanent/permanent-lottery-config-list.json
  - /kcfinder/js/helper.js
  - /key.json
  - /keys.json
  - /kkrp/site/info
  - /kkrps/im_group/*b
  - /km.asmx/getPlatParam
  - /langConfig.js
  - /language/en-GB/en-GB.xml
  - /language/index.html
  - /lanren/css/global.css
  - /legal/currency/set
  - /lib/assets/compiled/rails-ujs.js
  - /lib/client/etc/hometu.jpg
  - /lib/index.js
  - /license.txt
  - /loan
  - /login
  - /login/img/nyyh/chkjs.js
  - /loginMe
  - /logs
  - /m
  - /m/ticker/usdtqc
  - /magento/*b
  - /magento_version
  - /main
  - /manager
  - /market/getStockBaseInfo
  - /market/market-ws/iframe.html
  - /media/system/js/core.js
  - /member
  - /member/js/lang_zh_CN.js
  - /members
  - /members/login
  - /mentions-legales
  - /mentionslegales
  - /misc
  - /modular/sortable.esm.js
  - /modules
  - /modules/columnadverts/
  - /modules/comment/
  - /mssql
  - /mt
  - /mtja.html
  - /myConfig.js
  - /myadmin
  - /mysql
  - /mysqladmin
  - /mysqli
  - /mytio/config/base
  - /n/news/banner
  - /new
  - /new-site
  - /newfolder
  - /newsite
  - /nyyh/*b
  - /oci8
  - /ocpu/library/base/R/do.call/json
  - /odbc
  - /old
  - /old-site
  - /old-wp
  - /old/*b
  - /old1
  - /old2
  - /old_files
  - /oldsite
  - /oldsiteback
  - /oldsitehere
  - /oldwebsite
  - /openapi.json
  - /openapi.yaml
  - /otc
  - /other/codepay/js/codepay_util.js
  - /pages/admin
  - /pages/console/*b
  - /password_resets/new
  - /php
  - /php.ini
  - /phpMyAdmin
  - /phpinfo
  - /phpmyadmin
  - /phpmyadmin/*b
  - /phpmyinfo
  - /plesk-stat
  - /plugins
  - /plugins/*b
  - /plus
  - /pma
  - /portal
  - /portal/index/protocol.html
  - /postgre
  - /products.json
  - /project
  - /protal
  - /proxy/games
  - /proxy/settings
  - /public/*b
  - /radio.txt
  - /resources/css/headernav.css
  - /resources/main/common.js
  - /room/getRoomBangFans
  - /room/script/face.js
  - /roundcube
  - /rss/*b
  - /s_api/basic/*b
  - /secret.json
  - /secrets.json
  - /secrets.yml
  - /server-status
  - /server/php
  - /service
  - /service/extdirect
  - /settings.py
  - /sftp-config.json
  - /sftp.json
  - /shop
  - /shop/*b
  - /sign-in
  - /simpla
  - /site
  - /site.js
  - /site/get-hq
  - /site_old
  - /sitebackup
  - /sites/default/files
  - /sitio
  - /sito
  - /skin/common_files/lib/jquery.cookie.js
  - /skin/main/onload.js
  - /sql
  - /sqlite
  - /sqlite3
  - /sqlsrv
  - /src
  - /staging
  - /staging/*b
  - /static
  - /static/*b
  - /statics/js/API.js
  - /stock/search
  - /store
  - /store/*b
  - /stylesheets/archive.css
  - /subdrivers
  - /swagger-ui
  - /swagger.*b
  - /swagger/*b
  - /sysShell
  - /system
  - /tables
  - /telescope/requests
  - /temp
  - /template/920ka/*b
  - /template/css/login.css
  - /template/js/comm/Confrim.js
  - /template/tmp1/js/common.js
  - /templates
  - /templates/beez3
  - /templates/index.html
  - /templates/system/css/system.css
  - /test
  - /test/*b
  - /test_404_page
  - /testing
  - /tests
  - /themes
  - /themes/README.txt
  - /third_party
  - /tinc
  - /tmb/
  - /tmp
  - /tmpl
  - /tmps/
  - /toor.pho
  - /tslib.js
  - /ui/login
  - /underscore
  - /up/
  - /upload/
  - /upload/eupload
  - /upload/image/
  - /uploadify/*b
  - /uploads
  - /user/Login
  - /user/getAllNicknames
  - /user/userlist
  - /users
  - /users/new
  - /v1
  - /v1/management/tenant/getSpeedDomain
  - /v1/swagger.*b
  - /v2
  - /v2/_catalog
  - /v2/swagger.*b
  - /var/cache/mage--2
  - /var/resource_config.json
  - /vendor/
  - /views/commData/commonSite.js
  - /wallet.dat
  - /wallet.json
  - /wallets.json
  - /wap/api/exchangerateuserconfig!get.action
  - /wap/trading/get_newallorder_ajax
  - /web
  - /web/api/getBanner
  - /webadmin
  - /webapp
  - /website/blog
  - /widwsisw/
  - /wls-wsat/CoordinatorPortType/
  - /wordpress
  - /wordpress-old
  - /wordpress/license.txt
  - /wordpress1
  - /wp
  - /wp-admin
  - /wp-admin/*b
  - /wp-config
  - /wp-config-backup
  - /wp-config-backup1.txt
  - /wp-config-good
  - /wp-config-sample.php~
  - /wp-config.*b
  - /wp-config_backup
  - /wp-config_good
  - /wp-configbak
  - /wp-config~
  - /wp-content
  - /wp-content/*b
  - /wp-includes
  - /wp-includes/*b
  - /wp-json
  - /wp-json/*b
  - /wp-loading.phtml
  - /wp-old
  - /wp/license.txt
  - /wp1
  - /wp2
  - /www
  - /www.rar
  - /xianyu/*b
  - /xml
  - /xxsssseee
  - /xy
  - /xy/image/jiantou.png
  - /zso,php
  - /zso1,php
  - MicroStrategyWS/happyaxis.jsp

post:
  - '*a.php'
  - '*a/alfacgiapi/*b'
  - '*a/bin/sh'
  - '*a/debug/default/view'
  - '*a/mt-xmlrpc.cgi'
  - '*a/perl.alfa'
  - '*a/render/widget_php'
  - '*a/server/php'
  - /
  - /.env
  - /FCKeditor/editor/filemanager/connectors/asp/connector.asp
  - /_ignition/execute-solution
  - /alfacgiapi/*b
  - /api/app/config_new
  - /api/system/system/config/get
  - /api/v2/cmdb/system/admin/admin
  - /auth/oauth/token
  - /bin/bash
  - /bin/sh
  - /core/.env
  - /debug/default/view
  - /index.php/api/other/appSetting
  - /login/kefuxian.mvc
  - /melody/api/v1/pageconfig/list
  - /mt-xmlrpc.cgi
  - /paypal/transparent/requestSecureToken
  - /user/getAllNicknames
  - /wap/banner/details
  - /wp-config.php-backup
  - /wp-content/plugins/php-event-calendar/server/file-uploader
  - /wp-json/wp_live_chat_support/v1/remote_upload

delete:
  - /contacts
