require 'rails_helper'

VULNERABILITY_TESTING_PATHS = %w[
  .ftpconfig
  /.env
  /.git
  /1
  /2018
  /2019
  /2019/wp-includes/wlwmanifest.xml
  /2020
  /2020/wp-includes/wlwmanifest.xml
  /2021
  /2022
  /DesktopModules/Admin/RadEditorProvider/DialogHandler.aspx
  /FCKeditor/editor/filemanager/connectors/test.html
  /Install/InstallWizard.aspx?__VIEWSTATE=
  /Public/Home/js/common.js
  /Public/home/common/js/index.js
  /Public/home/wap/css/qdgame.css
  /Templates/user/js/global.js
  /_wpeprivate/config.json
  /actuator/env
  /admin
  /admin/new
  /api/ApiHub/fetchJinse
  /api/Index/getLottery
  /app_master/telerik.web.ui.dialoghandler.aspx
  /auth
  /backup
  /bak
  /base/exchange_article/index/classid/1/id/1
  /bk
  /blog
  /blog/wp-includes/wlwmanifest.xml
  /cache
  /cdn-cgi/foobar
  /cgi-bin/fubar
  /cms
  /cms/wp-includes/wlwmanifest.xml
  /common/member/js/user.util.js
  /components/swim
  /contacts
  /demo/
  /demo/index.php/admin/
  /demo/rss/catalog/notifystock
  /demo/rss/catalog/review
  /demo/rss/order/new
  /dev/
  /dev/index.php/admin/
  /dev/rss/catalog/notifystock
  /dev/rss/catalog/review
  /dev/rss/order/new
  /env
  /fckeditor/editor/filemanager/connectors/test.html
  /files/
  /foo/phpunit/bar
  /gaocc/g445g
  /html/js/editor/fckeditor/editor/filemanager/connectors/test.html
  /images/
  /images/src_images_but_dianz_s.png
  /include/fckeditor/editor/filemanager/connectors/test.html
  /index.php/admin/
  /infe/rest/flash/getServerIP.json
  /js/basic.js
  /js/fckeditor/editor/filemanager/connectors/test.html
  /magento/index.php/admin/
  /magento/rss/catalog/notifystock
  /magento/rss/catalog/review
  /magento/rss/order/new
  /member/js/lang_zh_CN.js
  /new
  /new-site
  /news/wp-includes/wlwmanifest.xml
  /nyyh/game.css
  /old-site
  /old-wp
  /old/
  /old/index.php/admin/
  /old/rss/catalog/notifystock
  /old/rss/catalog/review
  /old/rss/order/new
  /phpMyAdmin
  /phpmyadmin/fubar
  /plugins/fubar
  /providers/htmleditorproviders/telerik/telerik.web.ui.dialoghandler.aspx
  /proxy/settings
  /public/appapi/images/error.jpg
  /public/h5static/js/main.js
  /rss/catalog/notifystock
  /rss/catalog/review
  /rss/order/new
  /sftp-config.json
  /shop/index.php/admin/
  /shop/rss/catalog/notifystock
  /shop/rss/catalog/review
  /shop/rss/order/new
  /site/wp-includes/wlwmanifest.xml
  /sites/all/libraries/fckeditor/editor/filemanager/connectors/test.html
  /sites/all/modules/fckeditor/fckeditor/editor/filemanager/connectors/test.html
  /sites/default/files/
  /sito/wp-includes/wlwmanifest.xml
  /staging/index.php/admin/
  /staging/rss/catalog/notifystock
  /staging/rss/catalog/review
  /staging/rss/order/new
  /static/data/thirdgames.json
  /static/home/js/rooms.js
  /static/home/static/js/login.js
  /static/wap/js/common.js
  /static/xianyu/js/bankCheck.js
  /store/index.php/admin/
  /store/rss/catalog/notifystock
  /store/rss/catalog/review
  /store/rss/order/new
  /test/
  /test/index.php/admin/
  /test/rss/catalog/notifystock
  /test/rss/catalog/review
  /test/rss/order/new
  /uploads/
  /web/wp-includes/wlwmanifest.xml
  /webadmin
  /website/wp-includes/wlwmanifest.xml
  /wordpress
  /wordpress/wp-includes/wlwmanifest.xml
  /wp
  /wp-admin
  /wp-admin/css/
  /wp-booking.php
  /wp-config-backup.txt
  /wp-config-good
  /wp-config.bak
  /wp-config.good
  /wp-config.php-bak
  /wp-config.php-original
  /wp-config.php_
  /wp-config.php_1
  /wp-config.php_Old
  /wp-config.php_bak
  /wp-config.php_new
  /wp-config.php_orig
  /wp-config.php_original
  /wp-config.phporiginal
  /wp-config.php~
  /wp-config_good
  /wp-content/
  /wp-content/mu-plugins/db-safe-mode.php
  /wp-content/plugins/wpdiscuz/themes/default/style-rtl.css
  /wp-includes/css/wp-config.php
  /wp-includes/wlwmanifest.xml
  /wp-json
  /wp-json/wp/v2/users
  /wp/wp-includes/wlwmanifest.xml
  /wp1
  /wp1/wp-includes/wlwmanifest.xml
  /wp2
  /wp2/wp-includes/wlwmanifest.xml
  /www.rar
  /www.sql
  /www.sql.gz
  /www.sql.zon
  /xmlrpc.php
  /xxsssseee
].freeze

RSpec.describe "teapot routes", type: :routing do
  VULNERABILITY_TESTING_PATHS.each do |path|
    it "routes GET #{path} to the teapot controller" do
      expect(get(path)).to route_to('iron_teapot/teapots#coffee')
    end
  end

  it "routes POST / to the teapot controller" do
    expect(post('/')).to route_to('iron_teapot/teapots#coffee')
  end
end
